In [64]:
import os
import glob
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
from dotenv import load_dotenv 
import seaborn as sns

load_dotenv() # add t his line
name=os.getenv('NAME_')
name=name.split(",")
#path=[r"C:Blow_nose",r"C:Brush_hair", r"C:Drink_water"]
df = pd.DataFrame()
k = 0
#os.getcwd()


Path es una lista con los nombres de las carpetas con las actividades y debe colocarse el nombre del disco donde se almacena + : + nombre de la actividad. 

Ejemplo: 

path=[r"D:Blow_nose",r"D:Brush_hair", r"D:Brush_teeth", r"Drink_water",r"Dusting",r"Eat_meal",r"Ironing", r"Open_a_bottle", r"Open_a_box",r"Phone_call",r"Put_on_a_jacket",r"Put_on_a_shoe",r"Put_on_glasses",r"Salute",r"Sit_down",r"Sneeze_cough",r"Stand_up",r"Take_off_a_jacket",r"Take_off_a_shoe",r"Take_off_glasses",r"Type_on_a_keyboard",r"Whasing_dishes",r"Whasing_hands",r"Wrinting" ]

In [65]:
path=os.getenv('PATH_')
for p in name:
    os.chdir(path)
    os.chdir(p)
    file_extension = '.csv'
    all_filenames = [i for i in glob.glob(f"*{file_extension}")]
    for f in all_filenames:
        temp = pd.read_csv(f, names=['x', 'y', 'z'])
        temp['sample'] = k
        temp['activity'] = f'{p[2:]}'
        temp['filename'] = f'{f}'
        temp=temp[0:30]


        df = df.append([temp], ignore_index=True)
        k = k + 1
print(df)        


C:\Users\Daritza Teheran\AppData\Local\Temp\ipykernel_5652\219264996.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append([temp], ignore_index=True)
C:\Users\Daritza Teheran\AppData\Local\Temp\ipykernel_5652\219264996.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append([temp], ignore_index=True)
C:\Users\Daritza Teheran\AppData\Local\Temp\ipykernel_5652\219264996.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append([temp], ignore_index=True)
C:\Users\Daritza Teheran\AppData\Local\Temp\ipykernel_5652\219264996.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append([temp], ignore_

          x     y     z  sample     activity             filename
0      24.0 -61.0  28.0       0    Blow_nose   blow_nose_10_0.csv
1      22.0 -61.0  25.0       0    Blow_nose   blow_nose_10_0.csv
2      44.0 -62.0  26.0       0    Blow_nose   blow_nose_10_0.csv
3      41.0 -58.0  29.0       0    Blow_nose   blow_nose_10_0.csv
4      36.0 -52.0  25.0       0    Blow_nose   blow_nose_10_0.csv
...     ...   ...   ...     ...          ...                  ...
22945   2.0  31.0  43.0     764  Drink_water  drink_water_9_4.csv
22946  -1.0  31.0  42.0     764  Drink_water  drink_water_9_4.csv
22947  -8.0  31.0  39.0     764  Drink_water  drink_water_9_4.csv
22948 -11.0  31.0  38.0     764  Drink_water  drink_water_9_4.csv
22949 -13.0  31.0  39.0     764  Drink_water  drink_water_9_4.csv

[22950 rows x 6 columns]


In [66]:
V=list()
for r in range(k):
    sp = df[df['sample']==r]
    #
    sp = sp.drop(['activity',"sample","filename"], axis=1)
    values=sp.values
    V.append(values)
#final_seq = np.stack(V)
print(V)


[array([[ 24., -61.,  28.],
       [ 22., -61.,  25.],
       [ 44., -62.,  26.],
       [ 41., -58.,  29.],
       [ 36., -52.,  25.],
       [ 28., -52.,  22.],
       [ 30., -54.,  25.],
       [ 28., -61.,  22.],
       [ 21., -60.,  23.],
       [ 15., -56.,  30.],
       [ 12., -57.,  23.],
       [ 14., -48.,  14.],
       [ 16., -42.,  15.],
       [ 12., -38.,  17.],
       [  3., -42.,  21.],
       [ -7., -46.,  17.],
       [-13., -46.,  35.],
       [ -9., -50.,  44.],
       [-11., -52.,  34.],
       [-12., -48.,  45.],
       [ 10., -51.,  49.],
       [ 11., -52.,  43.],
       [ 10., -47.,  45.],
       [ -1., -41.,  46.],
       [  8., -42.,  49.],
       [ 16., -41.,  57.],
       [  9., -36.,  56.],
       [  3., -31.,  48.],
       [ -6., -40.,  42.],
       [ 18., -47.,  44.]]), array([[ 79., -24.,   9.],
       [ 76., -26.,   7.],
       [ 79., -29.,  13.],
       [ 78., -34.,   7.],
       [ 69., -32.,  17.],
       [ 63., -36.,   9.],
       [ 49., -31.,  16.]

In [ ]:
len_V = []
for one_V in V:
    len_V.append(len(one_V))
l=pd.Series(len_V)
l.describe()
#Conclusión las muestras no tienen el mismo tamaño se vuelve loco?

In [ ]:

final_seq = np.stack(V)

In [67]:
print(V[0])
db = DBSCAN(eps=0.5, min_samples=20).fit(V)

[[ 24. -61.  28.]
 [ 22. -61.  25.]
 [ 44. -62.  26.]
 [ 41. -58.  29.]
 [ 36. -52.  25.]
 [ 28. -52.  22.]
 [ 30. -54.  25.]
 [ 28. -61.  22.]
 [ 21. -60.  23.]
 [ 15. -56.  30.]
 [ 12. -57.  23.]
 [ 14. -48.  14.]
 [ 16. -42.  15.]
 [ 12. -38.  17.]
 [  3. -42.  21.]
 [ -7. -46.  17.]
 [-13. -46.  35.]
 [ -9. -50.  44.]
 [-11. -52.  34.]
 [-12. -48.  45.]
 [ 10. -51.  49.]
 [ 11. -52.  43.]
 [ 10. -47.  45.]
 [ -1. -41.  46.]
 [  8. -42.  49.]
 [ 16. -41.  57.]
 [  9. -36.  56.]
 [  3. -31.  48.]
 [ -6. -40.  42.]
 [ 18. -47.  44.]]


ValueError: Found array with dim 3. Estimator expected <= 2.

Azul z
rojo x
verde y

In [ ]:
for p in name:
    os.chdir(path)
    os.chdir(p)
    file_extension = '.csv'
    all_filenames = [i_ for i_ in glob.glob(f"*{file_extension}")]
    for f in all_filenames:
        #for i in [‘Walking’, ‘Jogging’, ‘Upstairs’, ‘Downstairs’, ‘Sitting’, ‘Standing’]:
        temp = pd.read_csv(f, names=['x', 'y', 'z'])
        #data = temp[['x-axis', 'y-axis', 'z-axis']]
        axis = temp["x"].plot(subplots=True, color="b", fontsize = 12)
        axis = temp["y"].plot(subplots=True, color="r", fontsize = 12)
        axis = temp["z"].plot(subplots=True, color="g", fontsize = 12)
    break

In [ ]:
path=os.getenv('PATH_')
def path_(p):
    os.chdir(path)
    os.chdir(p)
    file_extension = '.csv'
    all_filenames = [i for i in glob.glob(f"*{file_extension}")]
    for f in all_filenames:
        temp = pd.read_csv(f, names=['x', 'y', 'z'])
        axis = temp["x"].plot(subplots=True, color="b", fontsize = 12)
        axis = temp["y"].plot(subplots=True, color="r", fontsize = 12)
        axis = temp["z"].plot(subplots=True, color="g", fontsize = 12)
        #axis.set_title(p)


path_('D:Sit_down')
# path_('D:Brush_hair')
# path_('D:Phone_call')
# path_('D:Salute')